### ISSUE TITLE
getting parsererror

### ISSUE THREAD

**Issue by elrazez** [Minh-Trng/dex-buy-tools#1]
hey. when i try to run a command i get this:

```
Traceback (most recent call last):
  File "/usr/local/bin/dexbuy", line 8, in <module>
    sys.exit(dexbuy())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dexbuytools/__main__.py", line 36, in instant
    helper.buy_instantly(token_address)
  File "/usr/local/lib/python3.9/site-packages/dexbuytools/helpers/AvaxHelper.py", line 25, in buy_instantly
    super().perform_uniswapv2_style_buy(self.w3, self.dex_router, token_address, chain_data["MAIN_TOKEN_ADDRESS"])
  File "/usr/local/lib/python3.9/site-packages/dexbuytools/helpers/EvmBaseHelper.py", line 53, in perform_uniswapv2_style_buy
    tx = dex_router.functions[swap_method](
  File "/usr/local/lib/python3.9/site-packages/web3/contract.py", line 202, in __getitem__
    return getattr(self, function_name)
  File "/usr/local/lib/python3.9/site-packages/web3/contract.py", line 194, in __getattr__
    raise ABIFunctionNotFound(
web3.exceptions.ABIFunctionNotFound: ("The function 'swapExactETHForTokensSupportingFeeOnTransferTokens' was not found in this contract's abi. ", 'Are you sure you provided the correct contract abi?')
```

on the eth i think it's ok. but when using avax i get this. could you please tell me what should i do?

**Comment by Minh-Trng** [comment]
Hey, thanks for trying out this project :), 
I just pushed an update, that hopefully fixed it. This project uses the TraderJoe-DEX for swapping on avax and the method-name is different compared to other Uniswap-forks ("swapExactAVAXForTokensSupportingFeeOnTransferTokens"). 

Feel free to try it again and tell me if you encounter any other errors :)

**Comment by elrazez** [comment]
hey! thanks for the fast deploy and reply!

yeah i guessed the same. now it's giving me this on both bsc and avax:

```
Traceback (most recent call last):
  File "/usr/local/bin/dexbuy", line 8, in <module>
    sys.exit(dexbuy())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dexbuytools/__main__.py", line 36, in instant
    helper.buy_instantly(token_address)
  File "/usr/local/lib/python3.9/site-packages/dexbuytools/helpers/BscHelper.py", line 26, in buy_instantly
    super().perform_uniswapv2_style_buy(self.w3, self.dex_router, token_address, chain_data["MAIN_TOKEN_ADDRESS"])
  File "/usr/local/lib/python3.9/site-packages/dexbuytools/helpers/EvmBaseHelper.py", line 34, in perform_uniswapv2_style_buy
    token_address = w3.toChecksumAddress(token_address)
AttributeError: 'tuple' object has no attribute 'toChecksumAddress'
```

**Comment by Minh-Trng** [comment]
yea, this time I introduced a comma where it doesnt belong in the EVMBaseHelper-Class. I hoped I could change it before you tried, but you beat me to it I guess 😅 

Anyway, I just amended the last commit and tried a swap on BSC, that worked successfully, so hopefully it works this time

**Comment by Minh-Trng** [comment]
and btw, buying on Ethereum isnt supposed to work right now, so I suggest you dont use this tool there. All others should be fine, but I have only tested it on BSC tbh.

**Comment by elrazez** [comment]
thanks again! yeah i don't need eth now. i tried on both avax and bsc and still getting the same error. i even deleted the old version and reinstalled but didn't work.

**Comment by Minh-Trng** [comment]
you were right, there was another mistake (makes me wonder why my BSC swap worked in the first place). Anyway, I have pushed another commit and successfully tried swapping avax for a tiny amount of usdc on TraderJoe. Give it another shot 👍

**Comment by elrazez** [comment]
it got fixed! thank you so much.

one more question: is it possible to set a default wallet and general parameters so we don't have to enter them everytime? the command would be shortened to this: `dexbuy instant bsc 0x3ee2200efb3400fabb9aacf31297cbdd1d435d47`

that makes things a lot faster

**Comment by Minh-Trng** [comment]
nice, glad it worked out for you :)

yes, by default the files in the folder ./dexbuytools/config are used (as seen [here](https://github.com/Minh-Trng/dex-buy-tools/blob/master/dexbuytools/config/__init__.py)). just fill them out without changing the names and you are good to go.

Keep in mind, that the 'AMOUNT'-value in buy_params.yml always refers to the chains main token (AVAX, BNB, etc) though, so on some chains you automatically buy more tokens worth in USD as on others if you just want to use the default buy_params.yml

**Comment by elrazez** [comment]
this is fire. thank you so much. give me your telegram. i am good at finding stuff. i'll send u good launches from time to time.

**Comment by Minh-Trng** [comment]
would appreciate it! :) 
let me know once you got it, so I can delete: @Miinhh

**Comment by Minh-Trng** [comment]
also working on a kind of bot right now, that buys all tokens that are posted for the first time in a telegram channel. will try to use it on a couple of those bigger call-channels: https://github.com/Minh-Trng/telegram-token-sniper 
(still some way to go before its useable though)

**Comment by elrazez** [comment]
yeah i saw it. would be happy to help and test out whenever possible. got ur tg. 

one question:
GAS_PRICE_BONUS: 1000000000 # 1 GWEI

how should i enter the bonus in here? is this the priority fee? so it should be entered like 200? (meaning 200 gwei)

**Comment by elrazez** [comment]
want to achieve something like this on avax. 

<img width="307" alt="Screen Shot 2022-02-07 at 19 53 24" src="https://user-images.githubusercontent.com/9767777/152828818-f40f1487-3ef5-4aaf-b3db-6f62ffd3eb66.png">

**Comment by elrazez** [comment]
accidentally closed this lol. hope u're still seeing it

**Comment by Minh-Trng** [comment]
> yeah i saw it. would be happy to help and test out whenever possible. got ur tg.
> 
> one question: GAS_PRICE_BONUS: 1000000000 # 1 GWEI
> 
> how should i enter the bonus in here? is this the priority fee? so it should be entered like 200? (meaning 200 gwei)



> yeah i saw it. would be happy to help and test out whenever possible. got ur tg.
> 
> one question: GAS_PRICE_BONUS: 1000000000 # 1 GWEI
> 
> how should i enter the bonus in here? is this the priority fee? so it should be entered like 200? (meaning 200 gwei)

the priority fee thing is fairly new (last August or something) and was introduced on Ethereum in the so called EIP-1559. Before that it looked like this:
![grafik](https://user-images.githubusercontent.com/46103853/152831341-77d80b32-3873-46d2-aa10-ac88f6246b35.png)

the GAS_PRICE_BONUS basically just adds 1 Gwei to the gas price of whatever is recommended from the network itself. Now for chains that use the EIP-1559 style (thought it was only Ethereum tbh) sending transactions in this old style still works, it basically is like setting gas price = max priority fee = max fee (see [here](https://ethereum.stackexchange.com/questions/109775/what-happens-if-maxpriorityfeepergas-and-maxfeepergas-are-set-to-same-value) )

**Comment by elrazez** [comment]
oh thank you i figured this but i think i didn't correctly explain. 

my question is that what's the gas price bonus unit. because i'm seeing u entered 1000000000. is this twei? wei? for example what is 100gwei in this unit. 100000000000?

**Comment by elrazez** [comment]
found out it's wei. u wrote in the comments but my blind eyes didn't see. thank you!

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
